# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
  - covr
  - rvest

r_github_packages:
  - r-lib/pkgdown

after_success:
  - Rscript -e 'covr::codecov()'

before_deploy:
  - Rscript -e 'devtools::install_github("nbenn/infx")'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: docs
