# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r:
  - oldrel
  - release

r_packages:
  - covr
  - rvest
  - devtools

r_github_packages:
  - r-lib/pkgdown

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'

before_deploy:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'devtools::install_github("nbenn/infx")'
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    condition: $TRAVIS_R_VERSION_STRING = "release"
  local_dir: docs
