# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
  - covr

script: 
  - |
    R CMD build .
    travis_wait 20 R CMD check infx*tar.gz --as-cran --no-manual

after_success:
  - Rscript -e 'covr::codecov()'
